highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
# url: 
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-katex
kramdown:
  math_engine: katex
markdown: kramdown
usemathjax: true
katex:
